// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CourseGroup struct {
	CourseGroupCode   string      `json:"courseGroupCode"`
	CourseCode        string      `json:"courseCode"`
	ProfessorUsername string      `json:"professorUsername"`
	Capacity          int         `json:"capacity"`
	Taken             int         `json:"taken"`
	Schedules         []*Schedule `json:"schedules"`
}

type CourseGroupInput struct {
	CourseCode      string `json:"courseCode"`
	CourseGroupCode string `json:"courseGroupCode"`
}

type Enrollment struct {
	StudentUsername     string              `json:"studentUsername"`
	AcademicHistoryCode string              `json:"academicHistoryCode"`
	CourseGroups        []*CourseGroupInput `json:"courseGroups"`
}

type Schedule struct {
	Day         string `json:"day"`
	Building    string `json:"building"`
	Classroom   string `json:"classroom"`
	TimeOfStart string `json:"timeOfStart"`
	TimeOfEnd   string `json:"timeOfEnd"`
}
